name: Testing

on:
  push:
    branches: [ develop, release ]
  pull_request:
    branches: [ develop ]

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Build library
      run: bundle exec rake compile
    - name: Run tests
      run: bundle exec rake spec
