name: Testing

on:
  push:
    branches: [ develop, release ]
  pull_request:
    branches: [ develop ]

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
    - name: repo checkout
    - uses: actions/checkout@v2

    - name: load ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0

    - name: load depends
      run: rake install_dependencies

    - name: build library
      run: rake compile

    - name: run tests
      run: rake spec
